const test = require('node:test');
const assert = require('node:assert/strict');

const shared = require('../src/subtitles.shared.js');

test('buildSubtitleUrl appends missing params and fmt', () => {
  const url = shared.buildSubtitleUrl(
    'https://www.youtube.com/api/timedtext?foo=bar&sparams=ip,ipbits',
    'zh-CN',
    'Chinese Manual',
    '.zh-CN',
    'json3'
  );

  assert.equal(url.includes('lang=zh-CN'), true);
  assert.equal(url.includes('name=Chinese%20Manual'), true);
  assert.equal(url.includes('vss_id=.zh-CN'), true);
  assert.equal(url.includes('fmt=json3'), true);
  assert.equal(url.includes('ip,ipbits'), true);
});

test('buildSubtitleUrl does not append name for asr tracks', () => {
  const url = shared.buildSubtitleUrl(
    'https://www.youtube.com/api/timedtext?kind=asr',
    'zh-CN',
    'Auto Track',
    'a.zh-CN',
    null
  );

  assert.equal(url.includes('name='), false);
});

test('matchTranslation picks nearest by timestamp within window', () => {
  const zhEntry = { start: 10.0, duration: 2.0 };
  const ptTrack = [
    { start: 7.5, text: 'distante' },
    { start: 10.2, text: 'correta' },
    { start: 12.8, text: 'tambem distante' }
  ];

  assert.equal(shared.matchTranslation(zhEntry, ptTrack), 'correta');
});

test('matchTranslation returns empty when outside allowed distance', () => {
  const zhEntry = { start: 30.0, duration: 1.0 };
  const ptTrack = [
    { start: 20.0, text: 'muito cedo' },
    { start: 35.0, text: 'muito tarde' }
  ];

  assert.equal(shared.matchTranslation(zhEntry, ptTrack), '');
});

test('matchTranslation returns empty for invalid inputs', () => {
  assert.equal(shared.matchTranslation(null, []), '');
  assert.equal(shared.matchTranslation({ start: '10' }, []), '');
  assert.equal(shared.matchTranslation({ start: 10 }, null), '');
});

test('extractJSONObject finds balanced braces', () => {
  const text = 'prefix { "a": { "b": 1 } } suffix';
  const result = shared.extractJSONObject(text, 7);
  assert.equal(result, '{ "a": { "b": 1 } }');
});

test('decodeHTMLEntities handles basic and numeric entities', () => {
  assert.equal(shared.decodeHTMLEntities('A &amp; B &lt; C &gt; D &quot; E &#39; F &apos; G'), 'A & B < C > D " E \' F \' G');
  assert.equal(shared.decodeHTMLEntities('&#65; &#x42;'), 'A B');
});

test('parseTracks filters and normalizes raw track data', () => {
  const raw = [
    { languageCode: 'zh', baseUrl: 'url1', name: { simpleText: 'Chinese' } },
    { languageCode: 'pt', baseUrl: 'url2', kind: 'asr' },
    { languageCode: 'en' } // no baseUrl
  ];
  const tracks = shared.parseTracks(raw);
  assert.equal(tracks.length, 2);
  assert.equal(tracks[0].name, 'Chinese');
  assert.equal(tracks[1].isAutoGenerated, true);
});

test('findChineseTrack prioritizes manual over auto', () => {
  const tracks = [
    { languageCode: 'zh', isAutoGenerated: true, name: 'Auto Zh' },
    { languageCode: 'zh', isAutoGenerated: false, name: 'Manual Zh' }
  ];
  const found = shared.findChineseTrack(tracks);
  assert.equal(found.name, 'Manual Zh');
});

test('parseJSON3 extracts text and timestamps correctly', () => {
  const data = {
    events: [
      { tStartMs: 1000, dDurationMs: 500, segs: [{ utf8: 'Hello' }, { utf8: ' world' }] },
      { tStartMs: 2000, segs: [{ utf8: 'Test' }] }
    ]
  };
  const entries = shared.parseJSON3(data);
  assert.equal(entries.length, 2);
  assert.equal(entries[0].start, 1.0);
  assert.equal(entries[0].duration, 0.5);
  assert.equal(entries[0].text, 'Hello world');
});

test('parseXML handles SRV3 format', () => {
  const xml = '<timedtext><body><p t="1000" d="2000">Line 1</p></body></timedtext>';
  const entries = shared.parseXML(xml);
  assert.equal(entries.length, 1);
  assert.equal(entries[0].start, 1.0);
  assert.equal(entries[0].duration, 2.0);
  assert.equal(entries[0].text, 'Line 1');
});

test('parseXML handles Legacy format', () => {
  const xml = '<transcript><text start="1.5" dur="2.5">Legacy Line</text></transcript>';
  const entries = shared.parseXML(xml);
  assert.equal(entries.length, 1);
  assert.equal(entries[0].start, 1.5);
  assert.equal(entries[0].duration, 2.5);
  assert.equal(entries[0].text, 'Legacy Line');
});

test('extractTracksFromHTML finds tracks in ytInitialPlayerResponse', () => {
  const html = 'var ytInitialPlayerResponse = { "captions": { "playerCaptionsTracklistRenderer": { "captionTracks": [{ "languageCode": "zh", "baseUrl": "url" }] } } };';
  const tracks = shared.extractTracksFromHTML(html);
  assert.equal(tracks.length, 1);
  assert.equal(tracks[0].languageCode, 'zh');
});
