/**
 * VLL Subtitles Module — YouTube caption extraction & parsing
 * Runs as a content script in the YouTube page context.
 *
 * Uses multiple strategies to reliably extract caption data:
 * 1. Parse from script tags (fresh page load)
 * 2. Fetch page HTML directly (SPA navigation fallback)
 * 3. Extract from ytcfg embedded data
 */

/* global chrome */

const VLL_Subtitles = (() => {

  // Cache sorted translation tracks by array reference to avoid re-sorting
  // on every subtitle match.
  const _translationTrackCache = new WeakMap();

  /**
   * Extract a complete JSON object from a string starting at a given position.
   * Uses bracket counting instead of regex to handle nested objects correctly.
   */
  function extractJSONObject(text, startIndex) {
    let depth = 0;
    let inString = false;
    let escape = false;

    for (let i = startIndex; i < text.length; i++) {
      const ch = text[i];

      if (escape) {
        escape = false;
        continue;
      }

      if (ch === '\\' && inString) {
        escape = true;
        continue;
      }

      if (ch === '"') {
        inString = !inString;
        continue;
      }

      if (inString) continue;

      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) {
          return text.substring(startIndex, i + 1);
        }
      }
    }

    return null;
  }

  /**
   * Extract caption tracks from a page HTML string.
   * Works with both script tag content and fetched HTML.
   */
  function extractTracksFromHTML(html) {
    // Strategy A: Find ytInitialPlayerResponse and extract full JSON
    const markers = [
      'ytInitialPlayerResponse',
      'var ytInitialPlayerResponse',
      'window["ytInitialPlayerResponse"]'
    ];

    for (const marker of markers) {
      const idx = html.indexOf(marker);
      if (idx === -1) continue;

      // Find the opening brace after the marker
      const braceIdx = html.indexOf('{', idx + marker.length);
      if (braceIdx === -1) continue;

      const jsonStr = extractJSONObject(html, braceIdx);
      if (!jsonStr) continue;

      try {
        const data = JSON.parse(jsonStr);
        const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (tracks && tracks.length > 0) {
          console.log('[VLL] Found tracks via ytInitialPlayerResponse');
          return parseTracks(tracks);
        }
      } catch (e) {
        console.warn('[VLL] JSON parse failed for', marker, e.message);
      }
    }

    // Strategy B: Find captionTracks array directly
    const ctIdx = html.indexOf('"captionTracks"');
    if (ctIdx !== -1) {
      // Find the opening bracket
      const bracketIdx = html.indexOf('[', ctIdx);
      if (bracketIdx !== -1) {
        // Find matching closing bracket
        let depth = 0;
        for (let i = bracketIdx; i < Math.min(bracketIdx + 50000, html.length); i++) {
          if (html[i] === '[') depth++;
          else if (html[i] === ']') {
            depth--;
            if (depth === 0) {
              try {
                const arr = JSON.parse(html.substring(bracketIdx, i + 1));
                if (arr.length > 0 && arr[0].baseUrl) {
                  console.log('[VLL] Found tracks via captionTracks array');
                  return parseTracks(arr);
                }
              } catch (e) { /* continue */ }
              break;
            }
          }
        }
      }
    }

    return [];
  }

  /**
   * Normalize raw track objects into our format.
   */
  function parseTracks(tracks) {
    return tracks.map(t => ({
      languageCode: t.languageCode || '',
      baseUrl: t.baseUrl || '',
      name: t.name?.simpleText || t.name?.runs?.[0]?.text || t.languageCode || '',
      kind: t.kind || '',
      isAutoGenerated: t.kind === 'asr',
      vssId: t.vssId || ''
    })).filter(t => t.baseUrl);
  }

  /**
   * Main extraction: try multiple strategies to find caption tracks.
   */
  async function extractCaptionTracks() {
    const videoId = getVideoId();
    if (!videoId) return [];

    // Strategy 1: Fetch via InnerTube API (Android client)
    // This is crucial because the Web client now requires complex PO Token (n-parameter)
    // validation which returns 0 bytes if missing. The Android client bypasses this.
    console.log('[VLL] Strategy 1: Fetching via InnerTube API (Android bypass)...');
    try {
      const response = await fetch('https://www.youtube.com/youtubei/v1/player?prettyPrint=false', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': 'com.google.android.youtube/20.10.38 (Linux; U; Android 14)'
        },
        body: JSON.stringify({
          context: {
            client: {
              clientName: 'ANDROID',
              clientVersion: '20.10.38'
            }
          },
          videoId: videoId
        })
      });
      
      if (response.ok) {
        const data = await response.json();
        const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (tracks && tracks.length > 0) {
          console.log(`[VLL] Found ${tracks.length} tracks via InnerTube API!`);
          return parseTracks(tracks);
        }
      } else {
        console.warn(`[VLL] InnerTube API returned HTTP ${response.status}`);
      }
    } catch (e) {
      console.warn('[VLL] InnerTube API fetch failed:', e.message);
    }

    // Strategy 2: Parse from current page script tags (Legacy fallback)
    console.log('[VLL] Strategy 2: Parsing script tags...');
    try {
      const scripts = document.querySelectorAll('script');
      for (const script of scripts) {
        const text = script.textContent;
        if (!text || text.length < 100) continue;
        if (!text.includes('captionTracks') && !text.includes('captions')) continue;

        const tracks = extractTracksFromHTML(text);
        if (tracks.length > 0) return tracks;
      }
    } catch (e) {
      console.warn('[VLL] Strategy 2 failed:', e.message);
    }

    // Strategy 3: Fetch page HTML directly (handles SPA navigation fallback)
    console.log('[VLL] Strategy 3: Fetching page HTML...');
    try {
      const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
        credentials: 'same-origin'
      });
      const html = await response.text();
      const tracks = extractTracksFromHTML(html);
      if (tracks.length > 0) return tracks;
    } catch (e) {
      console.warn('[VLL] Strategy 3 failed:', e.message);
    }

    return [];
  }

  /**
   * Find the best Chinese subtitle track.
   * Prefers manual captions over auto-generated.
   */
  function findChineseTrack(tracks) {
    const zhCodes = ['zh', 'zh-Hans', 'zh-CN', 'zh-Hant', 'zh-TW', 'zh-SG'];

    // Also check vssId which sometimes has the actual language info
    const isZh = (t) =>
      zhCodes.includes(t.languageCode) ||
      t.vssId?.startsWith('.zh') ||
      t.vssId?.startsWith('a.zh') ||
      t.name?.toLowerCase().includes('中文') ||
      t.name?.toLowerCase().includes('chinese') ||
      t.name?.toLowerCase().includes('chinês');

    // Prefer manual captions
    const manual = tracks.find(t => isZh(t) && !t.isAutoGenerated);
    if (manual) return manual;

    // Fall back to auto-generated
    const auto = tracks.find(t => isZh(t));
    return auto || null;
  }

  /**
   * Find Portuguese subtitle track.
   */
  function findPortugueseTrack(tracks) {
    const ptCodes = ['pt', 'pt-BR', 'pt-PT'];
    const isPt = (t) =>
      ptCodes.includes(t.languageCode) ||
      t.name?.toLowerCase().includes('português') ||
      t.name?.toLowerCase().includes('portuguese');

    return tracks.find(t => isPt(t)) || null;
  }

  /**
   * Decode HTML entities in subtitle text.
   */
  function decodeHTMLEntities(text) {
    const el = document.createElement('textarea');
    el.innerHTML = text;
    return el.value;
  }

  /**
   * Safely parse JSON from response text. Returns null if invalid.
   */
  function safeJSONParse(text) {
    if (!text || text.trim().length === 0) return null;
    try {
      return JSON.parse(text);
    } catch {
      return null;
    }
  }

  /**
   * Parse subtitle entries from JSON3 format data.
   */
  function parseJSON3(data) {
    if (!data || !data.events) return [];
    return data.events
      .filter(e => e.segs)
      .map(e => {
        const text = e.segs.map(s => s.utf8 || '').join('');
        return {
          start: (e.tStartMs || 0) / 1000,
          duration: (e.dDurationMs || 0) / 1000,
          text: text.replace(/\n/g, ' ').trim()
        };
      })
      .filter(e => e.text.length > 0);
  }

  /**
   * Parse subtitle entries from XML text.
   * Handles both legacy XML (<text start="sec" dur="sec">) 
   * and SRV3 XML (<p t="ms" d="ms">).
   */
  function parseXML(xmlText) {
    if (!xmlText || xmlText.trim().length === 0) return [];
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(xmlText, 'text/xml');
      
      // Check for parse errors
      const parseError = doc.querySelector('parsererror');
      if (parseError) return [];

      // Format 1: SRV3 Android format (<p t="1234" d="567">)
      const pElements = doc.querySelectorAll('p');
      if (pElements.length > 0) {
        return Array.from(pElements).map(el => {
          // Remove inner <s> tags or other formatting, keep text
          let rawText = el.innerHTML.replace(/<[^>]+>/g, '');
          return {
            start: parseFloat(el.getAttribute('t') || '0') / 1000,
            duration: parseFloat(el.getAttribute('d') || '0') / 1000,
            text: decodeHTMLEntities(rawText).replace(/\n/g, ' ').trim()
          };
        }).filter(e => e.text.length > 0);
      }

      // Format 2: Legacy format (<text start="12.3" dur="4.5">)
      const textElements = doc.querySelectorAll('text');
      if (textElements.length > 0) {
        return Array.from(textElements).map(el => ({
          start: parseFloat(el.getAttribute('start') || '0'),
          duration: parseFloat(el.getAttribute('dur') || '0'),
          text: decodeHTMLEntities(el.textContent || '').replace(/\n/g, ' ').trim()
        })).filter(e => e.text.length > 0);
      }

      return [];
    } catch (err) {
      console.warn('[VLL] XML parse error:', err.message);
      return [];
    }
  }

  /**
   * Ensure the timedtext URL has all required parameters.
   * YouTube sometimes provides baseUrls that need lang/name to work.
   */
  function buildSubtitleUrl(baseUrl, langCode, trackName, vssId, fmt) {
    // IMPORTANT: Do NOT use the URL/URLSearchParams classes here!
    // URLSearchParams will URL-encode the commas in YouTube's 'sparams' query
    // parameter (e.g. sparams=ip,ipbits -> sparams=ip%2Cipbits). This completely
    // invalidates the YouTube URL signature and causes the API to return 0 bytes.
    let url = baseUrl;
    
    // Ensure lang is set
    if (langCode && !url.includes('&lang=') && !url.includes('?lang=')) {
      url += '&lang=' + encodeURIComponent(langCode);
    }
    // Ensure name is set for manual tracks if missing
    if (trackName && !url.includes('&name=') && !url.includes('?name=') && !url.includes('&kind=asr')) {
      url += '&name=' + encodeURIComponent(trackName);
    }
    // Ensure vss_id is set
    if (vssId && !url.includes('&vss_id=') && !url.includes('?vss_id=')) {
      url += '&vss_id=' + encodeURIComponent(vssId);
    }
    // Set format if specified
    if (fmt) {
      // Remove any existing fmt parameter
      url = url.replace(/&fmt=[^&]*/g, '').replace(/\?fmt=[^&]*&/, '?');
      url += '&fmt=' + encodeURIComponent(fmt);
    }
    return url;
  }

  /**
   * Fetch and parse timed text from a caption track.
   * Tries multiple URL/format combinations.
   * @param {string} baseUrl - The timedtext API URL
   * @param {string} langCode - Language code (e.g. 'zh-CN')
   * @param {string} trackName - Track name
   * @param {string} vssId - VSS ID (e.g. '.zh-CN')
   */
  async function fetchSubtitleTrack(baseUrl, langCode, trackName, vssId) {
    console.log(`[VLL] Fetching subtitles for [${langCode}]`);
    console.log(`[VLL] Full baseUrl: ${baseUrl}`);

    // Build URL variations to try
    const urlVariations = [
      // Try with lang/name/vss_id params explicitly set
      buildSubtitleUrl(baseUrl, langCode, trackName, vssId, null),
      buildSubtitleUrl(baseUrl, langCode, trackName, vssId, 'json3'),
      buildSubtitleUrl(baseUrl, langCode, trackName, vssId, 'srv3'),
      buildSubtitleUrl(baseUrl, langCode, trackName, vssId, 'vtt'),
      // Try original URL as-is
      baseUrl
    ];

    // De-duplicate
    const uniqueUrls = [...new Set(urlVariations)];

    for (let i = 0; i < uniqueUrls.length; i++) {
      const fetchUrl = uniqueUrls[i];
      console.log(`[VLL] Attempt ${i + 1}/${uniqueUrls.length}: ${fetchUrl.substring(0, 120)}...`);

      try {
        const response = await fetch(fetchUrl);
        if (!response.ok) {
          console.warn(`[VLL] HTTP ${response.status}`);
          continue;
        }

        const text = await response.text();
        console.log(`[VLL] Response: ${text.length} chars`);

        if (!text || text.trim().length === 0) {
          console.warn('[VLL] Empty response, trying next...');
          continue;
        }

        // Try XML parse
        const xmlEntries = parseXML(text);
        if (xmlEntries.length > 0) {
          console.log(`[VLL] ✅ Parsed ${xmlEntries.length} entries (XML)`);
          return xmlEntries;
        }

        // Try JSON parse
        const jsonData = safeJSONParse(text);
        if (jsonData) {
          const jsonEntries = parseJSON3(jsonData);
          if (jsonEntries.length > 0) {
            console.log(`[VLL] ✅ Parsed ${jsonEntries.length} entries (JSON3)`);
            return jsonEntries;
          }
        }

        console.warn(`[VLL] Got ${text.length} chars but couldn't parse. First 200: ${text.substring(0, 200)}`);
      } catch (err) {
        console.warn(`[VLL] Fetch error: ${err.message}`);
      }
    }

    console.error('[VLL] ❌ All subtitle fetch attempts failed');
    return [];
  }

  /**
   * Fetch a translated version of a track.
   */
  async function fetchTranslatedTrack(baseUrl, targetLang) {
    try {
      // Use string appending to avoid corrupting the signature
      let url = baseUrl;
      if (!url.includes('&tlang=') && !url.includes('?tlang=')) {
        url += '&tlang=' + encodeURIComponent(targetLang);
      }

      const response = await fetch(url);
      if (!response.ok) return [];

      const text = await response.text();
      if (!text || text.trim().length === 0) return [];

      // Try XML first
      const xmlEntries = parseXML(text);
      if (xmlEntries.length > 0) return xmlEntries;

      // Try JSON
      const jsonData = safeJSONParse(text);
      if (jsonData) {
        const jsonEntries = parseJSON3(jsonData);
        if (jsonEntries.length > 0) return jsonEntries;
      }

      // Try JSON3 format explicitly
      let url2 = url.replace(/&fmt=[^&]*/g, '').replace(/\?fmt=[^&]*&/, '?') + '&fmt=json3';
      const response2 = await fetch(url2);
      if (response2.ok) {
        const text2 = await response2.text();
        const data2 = safeJSONParse(text2);
        if (data2) {
          const entries = parseJSON3(data2);
          if (entries.length > 0) return entries;
        }
      }

      return [];
    } catch (err) {
      console.warn('[VLL] Translation track fetch failed:', err.message);
      return [];
    }
  }

  /**
   * Main entry: load all subtitle data for the current video.
   * Pre-loads EVERYTHING before video plays.
   */
  async function loadAllSubtitles(targetLang = 'pt') {
    console.log('[VLL] === Starting subtitle loading ===');
    const tracks = await extractCaptionTracks();

    if (tracks.length === 0) {
      console.warn('[VLL] No caption tracks found for this video');
      return { zhTrack: [], ptTrack: [], tracks: [], videoId: getVideoId() };
    }

    console.log(`[VLL] Found ${tracks.length} caption tracks:`);
    tracks.forEach(t => console.log(`  - ${t.name} [${t.languageCode}] ${t.isAutoGenerated ? '(auto)' : '(manual)'}`));

    // Find Chinese track
    const zhMeta = findChineseTrack(tracks);
    let zhTrack = [];
    let ptTrack = [];

    if (zhMeta) {
      console.log(`[VLL] Loading Chinese subtitles: ${zhMeta.name} [${zhMeta.languageCode}]`);
      zhTrack = await fetchSubtitleTrack(zhMeta.baseUrl, zhMeta.languageCode, zhMeta.name, zhMeta.vssId);
      console.log(`[VLL] Loaded ${zhTrack.length} Chinese subtitle entries`);

      // Try to get translated track
      console.log(`[VLL] Loading ${targetLang} translation...`);
      ptTrack = await fetchTranslatedTrack(zhMeta.baseUrl, targetLang);
      console.log(`[VLL] Loaded ${ptTrack.length} translated entries`);
    } else {
      console.warn('[VLL] No Chinese track found. Available languages:',
        tracks.map(t => t.languageCode).join(', '));

      if (tracks.length > 0) {
        console.log(`[VLL] Trying first available track: ${tracks[0].name}`);
        zhTrack = await fetchSubtitleTrack(tracks[0].baseUrl, tracks[0].languageCode, tracks[0].name, tracks[0].vssId);
        console.log(`[VLL] Loaded ${zhTrack.length} entries from ${tracks[0].languageCode}`);
      }
    }

    // If translated track is still empty, try Portuguese track directly once.
    if (ptTrack.length === 0) {
      const ptMeta = findPortugueseTrack(tracks);
      if (ptMeta) {
        console.log('[VLL] Trying Portuguese track as fallback...');
        ptTrack = await fetchSubtitleTrack(ptMeta.baseUrl, ptMeta.languageCode, ptMeta.name, ptMeta.vssId);
      }
    }

    return {
      zhTrack,
      ptTrack,
      tracks,
      videoId: getVideoId()
    };
  }

  /**
   * Prepare translation entries for fast nearest timestamp lookup.
   */
  function getPreparedTranslationTrack(ptTrack) {
    if (!Array.isArray(ptTrack) || ptTrack.length === 0) return [];

    const cached = _translationTrackCache.get(ptTrack);
    if (cached) return cached;

    const prepared = ptTrack
      .filter(e => typeof e?.start === 'number' && typeof e?.text === 'string')
      .slice()
      .sort((a, b) => a.start - b.start);

    _translationTrackCache.set(ptTrack, prepared);
    return prepared;
  }

  /**
   * Get the current YouTube video ID.
   */
  function getVideoId() {
    const url = new URL(window.location.href);
    return url.searchParams.get('v') || '';
  }

  /**
   * Match a translated line to a Chinese line by timestamp proximity.
   */
  function matchTranslation(zhEntry, ptTrack) {
    if (!zhEntry || typeof zhEntry.start !== 'number') return '';

    const prepared = getPreparedTranslationTrack(ptTrack);
    if (prepared.length === 0) return '';

    // Lower-bound binary search for first translated line with start >= zh start.
    let lo = 0;
    let hi = prepared.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (prepared[mid].start < zhEntry.start) lo = mid + 1;
      else hi = mid;
    }

    const candidates = [];
    if (lo < prepared.length) candidates.push(prepared[lo]);
    if (lo > 0) candidates.push(prepared[lo - 1]);

    if (candidates.length === 0) return '';

    let best = candidates[0];
    let bestDiff = Math.abs(best.start - zhEntry.start);

    for (let i = 1; i < candidates.length; i++) {
      const diff = Math.abs(candidates[i].start - zhEntry.start);
      if (diff < bestDiff) {
        best = candidates[i];
        bestDiff = diff;
      }
    }

    // Adapt matching window slightly based on subtitle duration.
    const duration = typeof zhEntry.duration === 'number' ? zhEntry.duration : 0;
    const maxDiff = Math.max(1.0, Math.min(3.0, duration * 0.75 || 2.0));

    return bestDiff <= maxDiff ? best.text : '';
  }

  // Public API
  return {
    extractCaptionTracks,
    findChineseTrack,
    findPortugueseTrack,
    fetchSubtitleTrack,
    fetchTranslatedTrack,
    loadAllSubtitles,
    getVideoId,
    matchTranslation
  };
})();
