/* eslint-disable no-undef */
(function initVLLSubtitlesShared(root, factory) {
  const api = factory();

  root.VLL_SubtitlesShared = api;

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
  }
})(typeof globalThis !== 'undefined' ? globalThis : this, function createVLLSubtitlesShared() {
  'use strict';

  const translationTrackCache = new WeakMap();

  function buildSubtitleUrl(baseUrl, langCode, trackName, vssId, fmt) {
    let url = baseUrl;

    if (langCode && !url.includes('&lang=') && !url.includes('?lang=')) {
      url += '&lang=' + encodeURIComponent(langCode);
    }

    if (
      trackName &&
      !url.includes('&name=') &&
      !url.includes('?name=') &&
      !url.includes('&kind=asr') &&
      !url.includes('?kind=asr')
    ) {
      url += '&name=' + encodeURIComponent(trackName);
    }

    if (vssId && !url.includes('&vss_id=') && !url.includes('?vss_id=')) {
      url += '&vss_id=' + encodeURIComponent(vssId);
    }

    if (fmt) {
      url = url.replace(/&fmt=[^&]*/g, '').replace(/\?fmt=[^&]*&/, '?');
      url += '&fmt=' + encodeURIComponent(fmt);
    }

    return url;
  }

  function getPreparedTranslationTrack(ptTrack) {
    if (!Array.isArray(ptTrack) || ptTrack.length === 0) return [];

    const cached = translationTrackCache.get(ptTrack);
    if (cached) return cached;

    const prepared = ptTrack
      .filter(e => typeof e?.start === 'number' && typeof e?.text === 'string')
      .slice()
      .sort((a, b) => a.start - b.start);

    translationTrackCache.set(ptTrack, prepared);
    return prepared;
  }

  function matchTranslation(zhEntry, ptTrack) {
    if (!zhEntry || typeof zhEntry.start !== 'number') return '';

    const prepared = getPreparedTranslationTrack(ptTrack);
    if (prepared.length === 0) return '';

    let lo = 0;
    let hi = prepared.length;
    while (lo < hi) {
      const mid = (lo + hi) >> 1;
      if (prepared[mid].start < zhEntry.start) lo = mid + 1;
      else hi = mid;
    }

    const candidates = [];
    if (lo < prepared.length) candidates.push(prepared[lo]);
    if (lo > 0) candidates.push(prepared[lo - 1]);

    if (candidates.length === 0) return '';

    let best = candidates[0];
    let bestDiff = Math.abs(best.start - zhEntry.start);

    for (let i = 1; i < candidates.length; i++) {
      const diff = Math.abs(candidates[i].start - zhEntry.start);
      if (diff < bestDiff) {
        best = candidates[i];
        bestDiff = diff;
      }
    }

    const duration = typeof zhEntry.duration === 'number' ? zhEntry.duration : 0;
    const maxDiff = Math.max(1.0, Math.min(3.0, duration * 0.75 || 2.0));

    return bestDiff <= maxDiff ? best.text : '';
  }

  function decodeHTMLEntities(text) {
    if (!text) return '';
    return text.replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/&apos;/g, "'")
      .replace(/&#(\d+);/g, (match, dec) => String.fromCharCode(dec))
      .replace(/&#x([0-9a-fA-F]+);/g, (match, hex) => String.fromCharCode(parseInt(hex, 16)));
  }

  function extractJSONObject(text, startIndex) {
    let depth = 0;
    let inString = false;
    let escape = false;

    for (let i = startIndex; i < text.length; i++) {
      const ch = text[i];
      if (escape) {
        escape = false;
        continue;
      }
      if (ch === '\\' && inString) {
        escape = true;
        continue;
      }
      if (ch === '"') {
        inString = !inString;
        continue;
      }
      if (inString) continue;

      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) {
          return text.substring(startIndex, i + 1);
        }
      }
    }
    return null;
  }

  function parseTracks(tracks) {
    if (!Array.isArray(tracks)) return [];
    return tracks.map(t => ({
      languageCode: t.languageCode || '',
      baseUrl: t.baseUrl || '',
      name: t.name?.simpleText || t.name?.runs?.[0]?.text || t.languageCode || '',
      kind: t.kind || '',
      isAutoGenerated: t.kind === 'asr',
      vssId: t.vssId || '',
      _source: t._source || 'unknown'
    })).filter(t => t.baseUrl);
  }

  function extractTracksFromHTML(html) {
    const markers = [
      'ytInitialPlayerResponse',
      'var ytInitialPlayerResponse',
      'window["ytInitialPlayerResponse"]'
    ];

    for (const marker of markers) {
      const idx = html.indexOf(marker);
      if (idx === -1) continue;

      const braceIdx = html.indexOf('{', idx + marker.length);
      if (braceIdx === -1) continue;

      const jsonStr = extractJSONObject(html, braceIdx);
      if (!jsonStr) continue;

      try {
        const data = JSON.parse(jsonStr);
        const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (tracks && tracks.length > 0) {
          return parseTracks(tracks);
        }
      } catch (e) { /* ignore */ }
    }

    const ctIdx = html.indexOf('"captionTracks"');
    if (ctIdx !== -1) {
      const bracketIdx = html.indexOf('[', ctIdx);
      if (bracketIdx !== -1) {
        let depth = 0;
        for (let i = bracketIdx; i < Math.min(bracketIdx + 50000, html.length); i++) {
          if (html[i] === '[') depth++;
          else if (html[i] === ']') {
            depth--;
            if (depth === 0) {
              try {
                const arr = JSON.parse(html.substring(bracketIdx, i + 1));
                if (arr.length > 0 && arr[0].baseUrl) {
                  return parseTracks(arr);
                }
              } catch (e) { /* ignore */ }
              break;
            }
          }
        }
      }
    }

    return [];
  }

  function findChineseTrack(tracks) {
    const zhCodes = ['zh', 'zh-Hans', 'zh-CN', 'zh-Hant', 'zh-TW', 'zh-SG'];
    const isZh = (t) =>
      zhCodes.includes(t.languageCode) ||
      t.vssId?.startsWith('.zh') ||
      t.vssId?.startsWith('a.zh') ||
      t.name?.toLowerCase().includes('中文') ||
      t.name?.toLowerCase().includes('chinese') ||
      t.name?.toLowerCase().includes('chinês');

    const manual = tracks.find(t => isZh(t) && !t.isAutoGenerated);
    if (manual) return manual;
    return tracks.find(t => isZh(t)) || null;
  }

  function findPortugueseTrack(tracks) {
    const ptCodes = ['pt', 'pt-BR', 'pt-PT'];
    const isPt = (t) =>
      ptCodes.includes(t.languageCode) ||
      t.name?.toLowerCase().includes('português') ||
      t.name?.toLowerCase().includes('portuguese');
    return tracks.find(t => isPt(t)) || null;
  }

  function safeJSONParse(text) {
    if (!text || text.trim().length === 0) return null;
    try {
      return JSON.parse(text);
    } catch {
      return null;
    }
  }

  function parseJSON3(data) {
    if (!data || !data.events) return [];
    return data.events
      .filter(e => e.segs)
      .map(e => {
        const text = e.segs.map(s => s.utf8 || '').join('');
        return {
          start: (e.tStartMs || 0) / 1000,
          duration: (e.dDurationMs || 0) / 1000,
          text: text.replace(/\n/g, ' ').trim()
        };
      })
      .filter(e => e.text.length > 0);
  }

  function parseXML(xmlText) {
    if (!xmlText || xmlText.trim().length === 0) return [];

    const entries = [];
    const srv3Regex = /<p\s+[^>]*t="(\d+)"[^>]*d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
    let match;
    while ((match = srv3Regex.exec(xmlText)) !== null) {
      const text = match[3].replace(/<[^>]+>/g, '');
      entries.push({
        start: parseInt(match[1]) / 1000,
        duration: parseInt(match[2]) / 1000,
        text: decodeHTMLEntities(text).replace(/\n/g, ' ').trim()
      });
    }

    if (entries.length > 0) return entries.filter(e => e.text.length > 0);

    const legacyRegex = /<text\s+[^>]*start="([\d.]+)"[^>]*dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
    while ((match = legacyRegex.exec(xmlText)) !== null) {
      entries.push({
        start: parseFloat(match[1]),
        duration: parseFloat(match[2]),
        text: decodeHTMLEntities(match[3]).replace(/\n/g, ' ').trim()
      });
    }

    return entries.filter(e => e.text.length > 0);
  }

  return {
    buildSubtitleUrl,
    matchTranslation,
    decodeHTMLEntities,
    extractJSONObject,
    parseTracks,
    extractTracksFromHTML,
    findChineseTrack,
    findPortugueseTrack,
    safeJSONParse,
    parseJSON3,
    parseXML
  };
});
